### ISSUE TITLE
syncing svn repositories leads to error

### ISSUE THREAD

**Issue by aschleifer** [vcs-python/vcspull#338]
command output:
```
╰─ vcspull -c ./vcspull.yaml
Traceback (most recent call last):
  File "/home/aschleifer/.local/bin/vcspull", line 8, in <module>
    sys.exit(cli.cli())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/aschleifer/.local/lib/python3.10/site-packages/vcspull/cli.py", line 111, in update
    list(map(update_repo, found_repos))
  File "/home/aschleifer/.local/lib/python3.10/site-packages/vcspull/cli.py", line 147, in update_repo
    current_remote = r.remote(config_remote_name)
AttributeError: 'SubversionRepo' object has no attribute 'remote'
```

config:
```
/home/aschleifer/tmp/vcspull:
  config: 'svn+https://<svn_host>/svn/<repo_path>/trunk/config'
```

It does make the actual new svn checkout, but the error shows up.

On a side note I also noticed that for git repos you see the output of the git command when it is executed, but for svn you see nothing, which makes it difficult to see the progress when you pull big/slow repositories.

**Comment by tony** [comment]
Tests need to be added for this.
