### ISSUE TITLE
pipx - ModuleNotFoundError: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by Jasha10** [vcs-python/vcspull#412]
I'm getting a `ModuleNotFoundError` when running vcspull following a `pipx` install.

To reproduce:
```
$ pipx install vcspull
  installed package vcspull 1.20.2, installed using Python 3.11.3
  These apps are now globally available
    - vcspull
done! ✨ 🌟 ✨
$ vcspull
Traceback (most recent call last):
  File "/home/homestar/.local/bin/vcspull", line 5, in <module>
    from vcspull import cli
  File "/home/homestar/.local/pipx/venvs/vcspull/lib/python3.11/site-packages/vcspull/__init__.py", line 15, in <module>
    from . import cli  # NOQA
    ^^^^^^^^^^^^^^^^^
  File "/home/homestar/.local/pipx/venvs/vcspull/lib/python3.11/site-packages/vcspull/cli/__init__.py", line 17, in <module>
    from .sync import create_sync_subparser, sync
  File "/home/homestar/.local/pipx/venvs/vcspull/lib/python3.11/site-packages/vcspull/cli/sync.py", line 14, in <module>
    from ..config import filter_repos, find_config_files, load_configs
  File "/home/homestar/.local/pipx/venvs/vcspull/lib/python3.11/site-packages/vcspull/config.py", line 15, in <module>
    from vcspull.validator import is_valid_config
  File "/home/homestar/.local/pipx/venvs/vcspull/lib/python3.11/site-packages/vcspull/validator.py", line 4, in <module>
    from vcspull.types import RawConfigDict
  File "/home/homestar/.local/pipx/venvs/vcspull/lib/python3.11/site-packages/vcspull/types.py", line 4, in <module>
    from typing_extensions import NotRequired, TypedDict
ModuleNotFoundError: No module named 'typing_extensions'
```
```
$ pipx --version
1.2.0
```

**Comment by Jasha10** [comment]
This might be fixable by adding `typing_extensions` to `pyproject.toml` in the `[tool.poetry.dependencies]` section.

**Comment by Jasha10** [comment]
FYI @tony I've submitted a PR.
